# Generated by Django 5.2.3 on 2026-09-15 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0036_alter_churchmembership_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ministry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "color",
                    models.CharField(
                        default="#7c3aed",
                        help_text="Usada nos quadros e exportações.",
                        max_length=7,
                        verbose_name="Cor (hex)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="music_ministries",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_ministries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Líder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ministério",
                "verbose_name_plural": "Ministérios",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MinistryRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Função")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "ministry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="music.ministry",
                        verbose_name="Ministério",
                    ),
                ),
            ],
            options={
                "verbose_name": "Função do Ministério",
                "verbose_name_plural": "Funções dos Ministérios",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "artist",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Artista"
                    ),
                ),
                (
                    "youtube_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="YouTube ID"
                    ),
                ),
                (
                    "youtube_title",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Título no YouTube"
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, verbose_name="Thumbnail"),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Duração (s)"
                    ),
                ),
                (
                    "original_key",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Tom original"
                    ),
                ),
                (
                    "church_key",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Tom da congregação"
                    ),
                ),
                (
                    "bpm",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="BPM"
                    ),
                ),
                (
                    "time_signature",
                    models.CharField(
                        blank=True,
                        default="4/4",
                        max_length=10,
                        verbose_name="Compasso",
                    ),
                ),
                (
                    "chords",
                    models.TextField(blank=True, verbose_name="Acordes (bruto)"),
                ),
                (
                    "chords_json",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Acordes com timing"
                    ),
                ),
                ("lyrics", models.TextField(blank=True, verbose_name="Letra")),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Tags (separadas por vírgula)",
                    ),
                ),
                (
                    "times_played",
                    models.PositiveIntegerField(default=0, verbose_name="Vezes tocada"),
                ),
                (
                    "last_played",
                    models.DateField(blank=True, null=True, verbose_name="Última vez"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Música",
                "verbose_name_plural": "Músicas (Repertório)",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerRoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Data")),
                (
                    "time",
                    models.TimeField(blank=True, null=True, verbose_name="Horário"),
                ),
                (
                    "theme",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Tema do culto"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, verbose_name="Publicada (visível para músicos)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteer_rosters",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_rosters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escala de Voluntários",
                "verbose_name_plural": "Escalas de Voluntários",
                "ordering": ["-date", "time"],
            },
        ),
        migrations.CreateModel(
            name="RosterAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("CONFIRMED", "Confirmado"),
                            ("DECLINED", "Recusado"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "ministry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="music.ministry",
                        verbose_name="Ministério",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="music.ministryrole",
                        verbose_name="Função",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Voluntário",
                    ),
                ),
                (
                    "roster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="music.volunteerroster",
                        verbose_name="Escala",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atribuição de Escala",
                "verbose_name_plural": "Atribuições de Escala",
                "ordering": ["roster__date", "ministry__name", "role__name"],
            },
        ),
        migrations.CreateModel(
            name="WorshipSetlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "roster",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="setlist",
                        to="music.volunteerroster",
                        verbose_name="Escala",
                    ),
                ),
            ],
            options={"verbose_name": "Setlist", "verbose_name_plural": "Setlists",},
        ),
        migrations.CreateModel(
            name="SetlistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                (
                    "custom_key",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Tom (customizado)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas dinâmicas")),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="setlist_items",
                        to="music.song",
                        verbose_name="Música",
                    ),
                ),
                (
                    "setlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="music.worshipsetlist",
                        verbose_name="Setlist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Setlist",
                "verbose_name_plural": "Itens do Setlist",
                "ordering": ["order"],
            },
        ),
        migrations.AddConstraint(
            model_name="ministry",
            constraint=models.UniqueConstraint(
                fields=("church", "name"), name="unique_church_ministry_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="ministryrole",
            constraint=models.UniqueConstraint(
                fields=("ministry", "name"), name="unique_ministry_role_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="rosterassignment",
            constraint=models.UniqueConstraint(
                fields=("roster", "ministry", "role", "user"),
                name="unique_roster_ministry_role_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="setlistitem",
            constraint=models.UniqueConstraint(
                fields=("setlist", "order"), name="unique_setlist_item_order"
            ),
        ),
    ]
