# Generated by Django 5.2.3 on 2026-09-15 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0036_alter_churchmembership_role"),
        ("music", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Band",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "color",
                    models.CharField(
                        default="#7048e8",
                        help_text="Usada nos rótulos e filtros.",
                        max_length=7,
                        verbose_name="Cor (hex)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="music_bands",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_bands",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Líder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banda",
                "verbose_name_plural": "Bandas",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="song",
            name="band",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="songs",
                to="music.band",
                verbose_name="Banda",
            ),
        ),
        migrations.AddConstraint(
            model_name="band",
            constraint=models.UniqueConstraint(
                fields=("church", "name"), name="unique_church_band_name"
            ),
        ),
    ]
