# Generated by Django 5.2.3 on 2026-09-15 18:55

import cloudinary_storage.storage
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_band_song_band_band_unique_church_band_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="band",
            name="photo",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to=core.storage.church_upload_to("bands"),
                verbose_name="Foto da banda",
            ),
        ),
    ]
