# Generated by Django 5.2.3 on 2026-09-15 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0036_alter_churchmembership_role"),
        ("music", "0003_band_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BandSetlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Data")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                (
                    "theme",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Tema (opcional)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "band",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="setlists",
                        to="music.band",
                        verbose_name="Banda",
                    ),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="band_setlists",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_band_setlists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Setlist",
                "verbose_name_plural": "Setlists",
                "ordering": ["-date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="BandSetlistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                (
                    "custom_key",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Tom (customizado)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas dinâmicas")),
                (
                    "setlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="music.bandsetlist",
                        verbose_name="Setlist",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="band_setlist_items",
                        to="music.song",
                        verbose_name="Música",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Setlist",
                "verbose_name_plural": "Itens dos Setlists",
                "ordering": ["order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("setlist", "order"),
                        name="unique_band_setlist_item_order",
                    )
                ],
            },
        ),
    ]
