# Generated by Django 5.2.3 on 2026-09-24 18:15

from django.db import migrations, models


def seed_chord_status(apps, schema_editor):
    """Músicas já cadastradas com cifra (json ou texto) viram MANUAL; sem cifra,
    PENDING (ficam na fila do worker local de extração de acordes)."""
    Song = apps.get_model('music', 'Song')
    for song in Song.objects.filter(chord_status='PENDING').only(
        'id', 'chords', 'chords_json'
    ):
        has_chords = bool(getattr(song, 'chords_json', None)) or bool(
            (song.chords or '').strip()
        )
        if has_chords:
            Song.objects.filter(pk=song.pk).update(
                chord_status='MANUAL', chord_error='', chord_retries=0
            )


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0004_bandsetlist_bandsetlistitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="chord_error",
            field=models.TextField(
                blank=True, default="", verbose_name="Erro da extração"
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="chord_processed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Processado em"
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="chord_retries",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Tentativas de extração"
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="chord_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Fila (aguardando extração)"),
                    ("PROCESSING", "Processando"),
                    ("COMPLETED", "Concluída"),
                    ("FAILED", "Falhou"),
                    ("MANUAL", "Manual"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
                verbose_name="Status da cifra",
            ),
        ),
        migrations.RunPython(seed_chord_status, migrations.RunPython.noop),
    ]
