# Generated by Django 5.2.3 on 2026-09-24 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0005_song_chord_error_song_chord_processed_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuário que adicionou a música ao repertório.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_songs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
    ]
