# Generated by Django 5.2.3 on 2026-09-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0006_song_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="bandsetlist",
            name="is_private",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Quando privado, só o usuário que criou o setlist consegue vê-lo.",
                verbose_name="Privado",
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="is_private",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Quando privado, só o usuário que cadastrou a música consegue vê-la.",
                verbose_name="Privado",
            ),
        ),
    ]
