# Generated by Django 5.2.3 on 2026-08-27 20:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Data")),
                (
                    "service_description",
                    models.CharField(
                        help_text="Ex: Culto de Ensino, Culto de Ceia",
                        max_length=150,
                        verbose_name="Descrição do Culto / Serviço",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DIZIMO", "Dízimo"),
                            ("OFERTA", "Ofertas Gerais"),
                            ("CONSTRUCAO", "Construção"),
                            ("ESPECIAL", "Especiais"),
                            ("MISSOES", "Missões"),
                            ("MULHERES", "Mulheres"),
                            ("HOMENS", "Homens"),
                            ("JOVENS", "Jovens"),
                            ("ESC_BIBLICA", "Escola Bíblica"),
                            ("INFANTIL", "Infantil"),
                            ("ADOLESCENTES", "Adolescentes"),
                        ],
                        max_length=30,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_entries",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada",
                "verbose_name_plural": "Entradas",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FinancialExit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Data")),
                (
                    "description",
                    models.CharField(
                        help_text="Ex: Zeladoria, Energisa, Cagepa",
                        max_length=200,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DIZIMO", "Dízimo"),
                            ("OFERTA", "Ofertas Gerais"),
                            ("CONSTRUCAO", "Construção"),
                            ("ESPECIAL", "Especiais"),
                            ("MISSOES", "Missões"),
                            ("MULHERES", "Mulheres"),
                            ("HOMENS", "Homens"),
                            ("JOVENS", "Jovens"),
                            ("ESC_BIBLICA", "Escola Bíblica"),
                            ("INFANTIL", "Infantil"),
                            ("ADOLESCENTES", "Adolescentes"),
                        ],
                        max_length=30,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor"
                    ),
                ),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="receipts/",
                        verbose_name="Comprovante",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_exits",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saída",
                "verbose_name_plural": "Saídas",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tither",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nome")),
                (
                    "is_anonymous",
                    models.BooleanField(default=False, verbose_name="Anônimo"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tithers",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dizimista",
                "verbose_name_plural": "Dizimistas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyClosing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Ano")),
                (
                    "month",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Mês",
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="Fechado"),
                ),
                (
                    "previous_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Saldo Anterior",
                    ),
                ),
                (
                    "total_entries",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Total de Entradas",
                    ),
                ),
                (
                    "total_exits",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Total de Saídas",
                    ),
                ),
                (
                    "final_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Saldo Final",
                    ),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_closings",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fechamento Mensal",
                "verbose_name_plural": "Fechamentos Mensais",
                "unique_together": {("church", "year", "month")},
            },
        ),
        migrations.CreateModel(
            name="TitheRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Ano")),
                (
                    "month",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Mês",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor"
                    ),
                ),
                (
                    "tither",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tithe_records",
                        to="finance.tither",
                        verbose_name="Dizimista",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Dízimo",
                "verbose_name_plural": "Registros de Dízimos",
                "ordering": ["-year", "-month"],
                "unique_together": {("tither", "year", "month")},
            },
        ),
    ]
