# Generated by Django 5.2.3 on 2026-08-28 13:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Título")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bill", "Conta fixa"),
                            ("deadline", "Prazo / Vencimento"),
                            ("meeting", "Reunião"),
                            ("event", "Evento"),
                        ],
                        default="event",
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "repeat_monthly",
                    models.BooleanField(
                        default=False, verbose_name="Recorre mensalmente"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        help_text="Preenchido quando o evento não recorre mensalmente.",
                        null=True,
                        verbose_name="Data (evento pontual)",
                    ),
                ),
                (
                    "month",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Mês (recorrente)",
                    ),
                ),
                (
                    "day",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="Dia (recorrente)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento do Calendário",
                "verbose_name_plural": "Eventos do Calendário",
                "ordering": ["-created_at"],
            },
        ),
    ]
