# Generated by Django 5.2.3 on 2026-08-28 13:58

from django.db import migrations
from django.db.models import Count


def seed_default_calendar_events(apps, schema_editor):
    """Semeia os eventos padrão recorrentes para congregações já ativas."""
    Church = apps.get_model('accounts', 'Church')
    CalendarEvent = apps.get_model('finance', 'CalendarEvent')

    DEFAULTS = [
        ('Energisa', 'bill', 10),
        ('Cagepa (água)', 'bill', 15),
        ('Internet', 'bill', 20),
        ('Envio do relatório (Convenção Regional)', 'deadline', 5),
    ]

    for church in Church.objects.filter(status='ACTIVE'):
        if CalendarEvent.objects.filter(church=church, repeat_monthly=True).exists():
            continue
        for title, category, day in DEFAULTS:
            CalendarEvent.objects.get_or_create(
                church=church,
                title=title,
                category=category,
                repeat_monthly=True,
                day=day,
            )


def reverse_default_calendar_events(apps, schema_editor):
    CalendarEvent = apps.get_model('finance', 'CalendarEvent')
    CalendarEvent.objects.filter(repeat_monthly=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_calendarevent"),
    ]

    operations = [
        migrations.RunPython(
            seed_default_calendar_events,
            reverse_default_calendar_events,
        ),
    ]
