# Generated by Django 5.2.3 on 2026-09-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_seed_default_calendar_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialentry",
            name="category",
            field=models.CharField(
                choices=[
                    ("DIZIMO", "Dízimo"),
                    ("OFERTA", "Ofertas Gerais"),
                    ("VISAO_CORPORATIVA", "Visão Corporativa"),
                    ("CONSTRUCAO", "Construção"),
                    ("ESPECIAL", "Especiais"),
                    ("MISSOES", "Missões"),
                    ("MULHERES", "Mulheres"),
                    ("HOMENS", "Homens"),
                    ("JOVENS", "Jovens"),
                    ("ESC_BIBLICA", "Escola Bíblica"),
                    ("INFANTIL", "Infantil"),
                    ("ADOLESCENTES", "Adolescentes"),
                    ("CASAIS", "Casais"),
                ],
                max_length=30,
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="financialexit",
            name="category",
            field=models.CharField(
                choices=[
                    ("DIZIMO", "Dízimo"),
                    ("OFERTA", "Ofertas Gerais"),
                    ("VISAO_CORPORATIVA", "Visão Corporativa"),
                    ("CONSTRUCAO", "Construção"),
                    ("ESPECIAL", "Especiais"),
                    ("MISSOES", "Missões"),
                    ("MULHERES", "Mulheres"),
                    ("HOMENS", "Homens"),
                    ("JOVENS", "Jovens"),
                    ("ESC_BIBLICA", "Escola Bíblica"),
                    ("INFANTIL", "Infantil"),
                    ("ADOLESCENTES", "Adolescentes"),
                    ("CASAIS", "Casais"),
                ],
                max_length=30,
                verbose_name="Categoria",
            ),
        ),
    ]
