# Generated by Django 5.2.3 on 2026-09-01 14:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_church_pastoral_prebenda_percent"),
        ("finance", "0004_alter_financialentry_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Ano")),
                (
                    "month",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Mês",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("TREASURY_APPROVED", "Aprovado pela Tesouraria"),
                            ("LEADERSHIP_APPROVED", "Aprovado pela Liderança"),
                            ("REJECTED", "Rejeitado"),
                        ],
                        default="PENDING",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "checks",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Resultado dos checks"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Observação"
                    ),
                ),
                (
                    "treasury_approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tesouraria aprovou em"
                    ),
                ),
                (
                    "leadership_approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Liderança aprovou em"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "approved_by_leadership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprovado pela Liderança",
                    ),
                ),
                (
                    "approved_by_treasury",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprovado pela Tesouraria",
                    ),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_validations",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Validação Mensal",
                "verbose_name_plural": "Validações Mensais",
                "unique_together": {("church", "year", "month")},
            },
        ),
    ]
