# Generated by Django 5.2.3

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_monthlyvalidation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyvalidation",
            name="leadership_rejected_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Liderança rejeitou em"
            ),
        ),
        migrations.AddField(
            model_name="monthlyvalidation",
            name="rejected_by_leadership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Rejeitado pela Liderança",
            ),
        ),
        migrations.AddField(
            model_name="monthlyvalidation",
            name="rejected_by_treasury",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Rejeitado pela Tesouraria",
            ),
        ),
        migrations.AddField(
            model_name="monthlyvalidation",
            name="treasury_rejected_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Tesouraria rejeitou em"
            ),
        ),
    ]
