# Generated by Django 5.2.3 on 2026-09-02 17:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_monthlyvalidation_rejected_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyvalidation",
            name="treasury_photo_url",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Foto do signatário (Tesouraria)",
            ),
        ),
        migrations.AddField(
            model_name="monthlyvalidation",
            name="treasury_signature_url",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Assinatura digital (Tesouraria)",
            ),
        ),
    ]
