# Generated by Django 5.2.3 on 2026-09-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_monthlyvalidation_treasury_photo_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyvalidation",
            name="signature_hash",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="SHA-256 da imagem da assinatura digital.",
                max_length=64,
                verbose_name="Hash da Assinatura",
            ),
        ),
    ]
