# Generated by Django 5.2.3 on 2026-09-05 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_monthlyvalidation_signature_hash"),
    ]

    operations = [
        migrations.RemoveField(model_name="financialexit", name="receipt",),
    ]
