# Generated by Django 5.2.3 on 2026-09-09 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_church_calendar_public_hash_delete_churchevent"),
        ("finance", "0009_remove_financialexit_receipt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="audience",
            field=models.CharField(
                choices=[
                    ("GENERAL", "Agenda da Igreja (Secretaria)"),
                    ("FINANCE", "Financeiro (Tesouraria)"),
                ],
                default="FINANCE",
                help_text="GENERAL: visível a todos e na página pública. FINANCE: só tesouraria.",
                max_length=20,
                verbose_name="Audiência",
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="calendar_events_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descrição"),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="calendar_events",
                to="accounts.member",
                verbose_name="Membros envolvidos",
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="start_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Horário de início"
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="category",
            field=models.CharField(
                choices=[
                    ("bill", "Conta fixa"),
                    ("deadline", "Prazo / Vencimento"),
                    ("meeting", "Reunião"),
                    ("event", "Evento"),
                    ("culto", "Culto"),
                    ("ensaio", "Ensaio"),
                ],
                default="event",
                max_length=20,
                verbose_name="Categoria",
            ),
        ),
    ]
