# Generated by Django 5.2.3 on 2026-09-10 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0011_migrate_churchevent_to_calendarevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="end_time",
            field=models.TimeField(
                blank=True,
                help_text="Usado p/ blocos de horário (ex.: 9h às 12h).",
                null=True,
                verbose_name="Horário de fim",
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="repeat_end_date",
            field=models.DateField(
                blank=True,
                help_text="Último dia de repetição (opcional).",
                null=True,
                verbose_name="Fim da recorrência",
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="repeat_interval",
            field=models.PositiveIntegerField(
                default=1,
                help_text="1 = toda semana; 2 = quinzenal (âncora = date).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(2),
                ],
                verbose_name="Intervalo em semanas",
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="repeat_weekly",
            field=models.BooleanField(
                default=False, verbose_name="Recorre semanalmente"
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="weekdays",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Usado quando repeat_weekly=True.",
                verbose_name="Dias da semana (ISO: 0=Seg..6=Dom)",
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="date",
            field=models.DateField(
                blank=True,
                help_text="Evento pontual, ou âncora/início de eventos semanais/quinzenais.",
                null=True,
                verbose_name="Data (evento pontual)",
            ),
        ),
    ]
