# Generated by Django 5.2.3 on 2026-09-11 15:15

import cloudinary_storage.storage
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "finance",
            "0012_calendarevent_end_time_calendarevent_repeat_end_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="financialentry",
            name="receipt",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to=core.storage.church_upload_to("receipts"),
                verbose_name="Comprovante",
            ),
        ),
        migrations.AddField(
            model_name="financialexit",
            name="receipt",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to=core.storage.church_upload_to("receipts"),
                verbose_name="Comprovante",
            ),
        ),
    ]
