# Generated by Django 5.2.3 on 2026-09-14 17:06

import cloudinary_storage.storage
import core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0031_church_card_theme_member_whatsapp_public"),
        ("finance", "0013_financialentry_receipt_financialexit_receipt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Ano")),
                ("number", models.PositiveIntegerField(verbose_name="Número")),
                (
                    "receipt_type",
                    models.CharField(
                        choices=[
                            ("SAIDA", "Saída / Pagamento"),
                            ("ENTRADA", "Entrada / Doação"),
                        ],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                ("date", models.DateField(verbose_name="Data de emissão")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DIZIMO", "Dízimo"),
                            ("OFERTA", "Ofertas Gerais"),
                            ("VISAO_CORPORATIVA", "Visão Corporativa"),
                            ("CONSTRUCAO", "Construção"),
                            ("ESPECIAL", "Especiais"),
                            ("MISSOES", "Missões"),
                            ("MULHERES", "Mulheres"),
                            ("HOMENS", "Homens"),
                            ("JOVENS", "Jovens"),
                            ("ESC_BIBLICA", "Escola Bíblica"),
                            ("INFANTIL", "Infantil"),
                            ("ADOLESCENTES", "Adolescentes"),
                            ("CASAIS", "Casais"),
                        ],
                        help_text="Categoria usada quando o recibo também lança o movimento no caixa.",
                        max_length=30,
                        verbose_name="Categoria (lançamento automático)",
                    ),
                ),
                (
                    "favored_name",
                    models.CharField(max_length=150, verbose_name="Nome completo"),
                ),
                (
                    "favored_document",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="CPF / CNPJ"
                    ),
                ),
                (
                    "favored_rg",
                    models.CharField(blank=True, max_length=20, verbose_name="RG"),
                ),
                (
                    "favored_city",
                    models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
                ),
                (
                    "favored_state",
                    models.CharField(blank=True, max_length=2, verbose_name="UF"),
                ),
                (
                    "pix",
                    models.CharField(
                        blank=True, max_length=140, verbose_name="Chave PIX"
                    ),
                ),
                (
                    "auto_launched",
                    models.BooleanField(
                        default=False,
                        help_text="True quando o recibo também gerou o lançamento (entrada/saída).",
                        verbose_name="Lançado automaticamente no caixa",
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                        upload_to=core.storage.church_upload_to("receipts"),
                        verbose_name="PDF (2 vias)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_receipts",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Emitido por",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipts",
                        to="finance.financialentry",
                        verbose_name="Entrada vinculada",
                    ),
                ),
                (
                    "exit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipts",
                        to="finance.financialexit",
                        verbose_name="Saída vinculada",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_receipts",
                        to="accounts.member",
                        verbose_name="Membro vinculado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recibo Financeiro",
                "verbose_name_plural": "Recibos Financeiros",
                "ordering": ["-year", "-number"],
                "unique_together": {("church", "year", "number")},
            },
        ),
    ]
