# Generated by Django 5.2.3 on 2026-09-21 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0014_financialreceipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="repeat_monthly_ordinal",
            field=models.IntegerField(
                blank=True,
                help_text="1..5 = 1ª..5ª ocorrência; -1 = última do mês. Use com repeat_monthly_weekday.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Ocorrência no mês",
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="repeat_monthly_weekday",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Usado com repeat_monthly_ordinal p/ cultos de frequência (ex.: primeiro domingo do mês → ordinal=1, weekday=6).",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(6),
                ],
                verbose_name="Dia da semana (mensal por ocorrência)",
            ),
        ),
    ]
