# Generated by Django 5.2.3 on 2026-09-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0015_calendarevent_repeat_monthly_ordinal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Cor em hex (ex.: #228be6) exibida no calendário.",
                max_length=7,
                verbose_name="Cor",
            ),
        ),
    ]
