# Generated by Django 5.2.3 on 2026-09-29 20:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0040_growthgroup_acct_growth_church_weekday_idx_and_more"),
        ("finance", "0016_calendarevent_color"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="financialentry",
            index=models.Index(
                fields=["church", "date"], name="fin_entry_church_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialentry",
            index=models.Index(
                fields=["church", "created_at"], name="fin_entry_church_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialexit",
            index=models.Index(
                fields=["church", "date"], name="fin_exit_church_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialexit",
            index=models.Index(
                fields=["church", "created_at"], name="fin_exit_church_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialreceipt",
            index=models.Index(
                fields=["church", "date"], name="fin_receipt_church_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialreceipt",
            index=models.Index(
                fields=["church", "receipt_type"], name="fin_receipt_church_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monthlyclosing",
            index=models.Index(
                fields=["church", "year"], name="fin_close_church_year_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monthlyvalidation",
            index=models.Index(
                fields=["church", "year"], name="fin_valid_church_year_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monthlyvalidation",
            index=models.Index(
                fields=["church", "status"], name="fin_valid_church_status_idx"
            ),
        ),
    ]
