# Generated by Django 5.2.3 on 2026-08-27 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Church",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nome da Congregação"
                    ),
                ),
                (
                    "pastor_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Pastor Responsável"
                    ),
                ),
                (
                    "treasurer_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Tesoureiro Responsável",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone / WhatsApp"
                    ),
                ),
                ("cep", models.CharField(blank=True, max_length=9, verbose_name="CEP")),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Logradouro"
                    ),
                ),
                (
                    "number",
                    models.CharField(blank=True, max_length=20, verbose_name="Número"),
                ),
                (
                    "neighborhood",
                    models.CharField(blank=True, max_length=100, verbose_name="Bairro"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Cidade")),
                ("state", models.CharField(max_length=2, verbose_name="UF")),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="Latitude"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Longitude"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente de Aprovação"),
                            ("ACTIVE", "Ativa"),
                            ("REJECTED", "Rejeitada"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Cadastrado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={"verbose_name": "Igreja", "verbose_name_plural": "Igrejas",},
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Nome Completo"
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="Ativo")),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="Acesso Admin"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "church",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_account",
                        to="accounts.church",
                        verbose_name="Igreja Vinculada",
                    ),
                ),
            ],
            options={"verbose_name": "Usuário", "verbose_name_plural": "Usuários",},
        ),
    ]
