# Generated by Django 5.2.3 on 2026-09-01 14:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="church",
            name="pastoral_prebenda_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10.00"),
                help_text="Percentual da prebenda sobre o total arrecadado no mês.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Percentual da Prebenda Pastoral (%)",
            ),
        ),
    ]
