# Generated by Django 5.2.3 on 2026-09-04 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_church_pastoral_prebenda_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="church",
            name="accounting_category",
            field=models.CharField(
                blank=True,
                help_text="Categoria à qual os repasses da congregação são atribuídos na Sede.",
                max_length=100,
                null=True,
                verbose_name="Categoria Contábil do Repasse",
            ),
        ),
        migrations.AddField(
            model_name="church",
            name="church_type",
            field=models.CharField(
                choices=[
                    ("INDEPENDENT", "Igreja Independente / Sede"),
                    ("CONGREGATION", "Congregação"),
                ],
                default="CONGREGATION",
                max_length=20,
                verbose_name="Tipo de Igreja",
            ),
        ),
        migrations.AddField(
            model_name="church",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Congregações só são aprovadas após o fluxo de aprovação da Sede.",
                verbose_name="Aprovada pela Sede",
            ),
        ),
        migrations.AddField(
            model_name="church",
            name="parent_church",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="congregations",
                to="accounts.church",
                verbose_name="Igreja Sede (Independente)",
            ),
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nome")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone / WhatsApp"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Nascimento"
                    ),
                ),
                (
                    "baptism_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Batismo"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Ativo"), ("INACTIVE", "Inativo")],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members_directory",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membro",
                "verbose_name_plural": "Membros",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ChurchMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PASTOR", "Pastor(a)"),
                            ("SECRETARIA", "Secretário(a)"),
                            ("TESOUREIRO", "Tesoureiro(a)"),
                        ],
                        max_length=20,
                        verbose_name="Papel",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="church_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vínculo de Usuário",
                "verbose_name_plural": "Vínculos de Usuários",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "church"), name="unique_user_church_membership"
                    )
                ],
            },
        ),
    ]
