# Generated by Django 5.2.3 on 2026-09-04 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_backfill_church_types_and_memberships"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="church",
            field=models.ForeignKey(
                blank=True,
                help_text="Igreja em operação no momento (contexto ativo). A autorização é definida pelo ChurchMembership; User.church é apenas um ponteiro.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.church",
                verbose_name="Igreja Ativa (contexto)",
            ),
        ),
    ]
