# Generated by Django 5.2.3 on 2026-09-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_church"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountingCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Chave normalizada (ex.: CONGREGACAO_ABC).",
                        max_length=60,
                        unique=True,
                        verbose_name="Chave",
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="Rótulo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Categoria Contábil",
                "verbose_name_plural": "Categorias Contábeis",
                "ordering": ["label"],
            },
        ),
    ]
