# Generated by Django 5.2.3 on 2026-09-05 00:59

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_accountingcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="church_entry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACLAMACAO", "Aclamação"),
                    ("BATISMO", "Batismo"),
                    ("RECONCILIACAO", "Reconciliação"),
                    ("TRANSFERENCIA", "Carta de Transferência"),
                ],
                max_length=20,
                verbose_name="Forma de Entrada na Igreja",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="cpf",
            field=models.CharField(blank=True, max_length=14, verbose_name="CPF"),
        ),
        migrations.AddField(
            model_name="member",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="Foto"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="rg",
            field=models.CharField(blank=True, max_length=20, verbose_name="RG"),
        ),
        migrations.CreateModel(
            name="MinistryArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ministry_areas",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Área de Atuação",
                "verbose_name_plural": "Áreas de Atuação",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="member",
            name="ministry_areas",
            field=models.ManyToManyField(
                blank=True,
                related_name="members",
                to="accounts.ministryarea",
                verbose_name="Áreas de Atuação",
            ),
        ),
        migrations.AddConstraint(
            model_name="ministryarea",
            constraint=models.UniqueConstraint(
                fields=("church", "name"), name="unique_church_ministry_area"
            ),
        ),
    ]
