# Generated by Django 5.2.3 on 2026-09-08 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_member_church_entry_member_cpf_member_photo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberRelative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nome")),
                (
                    "kinship",
                    models.CharField(
                        choices=[
                            ("CONJUGE", "Cônjuge"),
                            ("PAI", "Pai"),
                            ("MAE", "Mãe"),
                            ("FILHO", "Filho(a)"),
                            ("IRMAO", "Irmão(ã)"),
                            ("AVO", "Avô(ó)"),
                            ("NETO", "Neto(a)"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Grau de Parentesco",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Nascimento"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Parente do Membro",
                "verbose_name_plural": "Parentes dos Membros",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="member",
            name="born_in_city",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Cidade de Nascimento (Naturalidade)",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="born_in_state",
            field=models.CharField(
                blank=True, max_length=2, verbose_name="UF de Nascimento"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="card_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Matrícula / Número da Carteirinha",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FUNDAMENTAL", "Ensino Fundamental"),
                    ("MEDIO", "Ensino Médio"),
                    ("SUPERIOR", "Ensino Superior"),
                    ("POS_GRADUACAO", "Pós-graduação"),
                ],
                max_length=20,
                verbose_name="Escolaridade",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="father_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Nome do Pai"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SOLTEIRO", "Solteiro(a)"),
                    ("CASADO", "Casado(a)"),
                    ("UNIAO_ESTAVEL", "União Estável"),
                    ("SEPARADO", "Separado(a)"),
                    ("DIVORCIADO", "Divorciado(a)"),
                    ("VIUVO", "Viúvo(a)"),
                ],
                max_length=20,
                verbose_name="Estado Civil",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="marriage_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data do Casamento"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="mother_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Nome da Mãe"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="profession",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Profissão / Ocupação"
            ),
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                condition=models.Q(("card_number__isnull", False)),
                fields=("church", "card_number"),
                name="unique_church_member_card_number",
            ),
        ),
        migrations.AddField(
            model_name="memberrelative",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relatives",
                to="accounts.member",
                verbose_name="Membro",
            ),
        ),
    ]
