# Generated by Django 5.2.3 on 2026-09-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_memberrelative_member_born_in_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="church_entry_other",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Forma de Entrada (outra)"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="church_entry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACLAMACAO", "Aclamação"),
                    ("BATISMO", "Batismo"),
                    ("RECONCILIACAO", "Reconciliação"),
                    ("TRANSFERENCIA", "Carta de Transferência"),
                    ("OUTRO", "Outro"),
                ],
                max_length=20,
                verbose_name="Forma de Entrada na Igreja",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SEM_ESCOLARIDADE", "Sem Escolaridade"),
                    ("FUNDAMENTAL", "Ensino Fundamental"),
                    ("MEDIO_INCOMPLETO", "Ensino Médio Incompleto"),
                    ("MEDIO", "Ensino Médio"),
                    ("SUPERIOR_INCOMPLETO", "Ensino Superior Incompleto"),
                    ("SUPERIOR", "Ensino Superior"),
                    ("POS_GRADUACAO", "Pós-graduação"),
                ],
                max_length=20,
                verbose_name="Escolaridade",
            ),
        ),
    ]
