# Generated by Django 5.2.3 on 2026-09-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0009_member_church_entry_other_alter_member_church_entry_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="church",
            name="card_back_phrase",
            field=models.TextField(
                blank=True, verbose_name="Frase do Verso da Carteirinha"
            ),
        ),
        migrations.AddField(
            model_name="church",
            name="card_front_phrase",
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name="Frase da Frente da Carteirinha",
            ),
        ),
        migrations.AddField(
            model_name="church",
            name="card_primary_color",
            field=models.CharField(
                blank=True,
                default="#0f766e",
                max_length=7,
                verbose_name="Cor Primária da Carteirinha",
            ),
        ),
        migrations.AddField(
            model_name="church",
            name="card_secondary_color",
            field=models.CharField(
                blank=True,
                default="#0ea5e9",
                max_length=7,
                verbose_name="Cor Secundária da Carteirinha",
            ),
        ),
        migrations.AddField(
            model_name="church",
            name="card_valid_until",
            field=models.DateField(
                blank=True, null=True, verbose_name="Carteirinha Válida até"
            ),
        ),
    ]
