# Generated by Django 5.2.3 on 2026-09-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_church_card_back_phrase_church_card_front_phrase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="cep",
            field=models.CharField(blank=True, max_length=9, verbose_name="CEP"),
        ),
        migrations.AddField(
            model_name="member",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
        ),
        migrations.AddField(
            model_name="member",
            name="complement",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Complemento"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="neighborhood",
            field=models.CharField(blank=True, max_length=100, verbose_name="Bairro"),
        ),
        migrations.AddField(
            model_name="member",
            name="number",
            field=models.CharField(blank=True, max_length=20, verbose_name="Número"),
        ),
        migrations.AddField(
            model_name="member",
            name="state",
            field=models.CharField(blank=True, max_length=2, verbose_name="UF"),
        ),
        migrations.AddField(
            model_name="member",
            name="street",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Rua / Avenida"
            ),
        ),
    ]
