# Generated by Django 5.2.3 on 2026-09-09 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_member_cep_member_city_member_complement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente de Recebimento"),
                            ("RECEIVED", "Recebida"),
                            ("CANCELED", "Cancelada"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Emitida em"),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Recebida em"
                    ),
                ),
                (
                    "canceled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Cancelada em"
                    ),
                ),
                ("member_name", models.CharField(max_length=150, verbose_name="Nome")),
                (
                    "member_cpf",
                    models.CharField(blank=True, max_length=14, verbose_name="CPF"),
                ),
                (
                    "member_rg",
                    models.CharField(blank=True, max_length=20, verbose_name="RG"),
                ),
                (
                    "member_birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Nascimento"
                    ),
                ),
                (
                    "member_baptism_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Batismo"
                    ),
                ),
                (
                    "member_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone / WhatsApp"
                    ),
                ),
                (
                    "member_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "member_profession",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Profissão / Ocupação"
                    ),
                ),
                (
                    "member_father_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Nome do Pai"
                    ),
                ),
                (
                    "member_mother_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Nome da Mãe"
                    ),
                ),
                (
                    "member_street",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Rua / Avenida"
                    ),
                ),
                (
                    "member_number",
                    models.CharField(blank=True, max_length=20, verbose_name="Número"),
                ),
                (
                    "member_complement",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Complemento"
                    ),
                ),
                (
                    "member_neighborhood",
                    models.CharField(blank=True, max_length=100, verbose_name="Bairro"),
                ),
                (
                    "member_city",
                    models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
                ),
                (
                    "member_state",
                    models.CharField(blank=True, max_length=2, verbose_name="UF"),
                ),
                (
                    "member_cep",
                    models.CharField(blank=True, max_length=9, verbose_name="CEP"),
                ),
                (
                    "member_notes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "canceled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_canceled",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cancelada por",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recebida por",
                    ),
                ),
                (
                    "source_church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_transfers",
                        to="accounts.church",
                        verbose_name="Igreja de Origem",
                    ),
                ),
                (
                    "source_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_out",
                        to="accounts.member",
                        verbose_name="Membro Transferido",
                    ),
                ),
                (
                    "target_church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transfers",
                        to="accounts.church",
                        verbose_name="Igreja de Destino",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transferência de Membro",
                "verbose_name_plural": "Transferências de Membros",
                "ordering": ["-issued_at"],
            },
        ),
    ]
