# Generated by Django 5.2.3 on 2026-09-09 12:30

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_membertransfer"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("RG", "RG"),
                            ("CPF", "CPF"),
                            ("RESIDENCE_PROOF", "Comprovante de Residência"),
                            ("OTHER", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        storage=accounts.models.MemberDocumentsStorage(),
                        upload_to="member_documents",
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Observações"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Enviado em"),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="accounts.member",
                        verbose_name="Membro",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enviado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento do Membro",
                "verbose_name_plural": "Documentos dos Membros",
                "ordering": ["-uploaded_at", "id"],
            },
        ),
    ]
