# Generated by Django 5.2.3 on 2026-09-09 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_memberdocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChurchEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Título")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                ("event_date", models.DateField(verbose_name="Data do evento")),
                (
                    "start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Horário de início"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="church_events",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="events",
                        to="accounts.member",
                        verbose_name="Membros envolvidos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento da Igreja",
                "verbose_name_plural": "Eventos da Igreja",
                "ordering": ["event_date", "start_time", "title"],
            },
        ),
    ]
