# Generated by Django 5.2.3 on 2026-09-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_churchevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="church",
            name="calendar_public_hash",
            field=models.CharField(
                blank=True,
                help_text="Hash único usado na URL pública do calendário da igreja.",
                max_length=32,
                null=True,
                unique=True,
                verbose_name="Hash público do Calendário",
            ),
        ),
    ]
