# Generated by Django 5.2.3 on 2026-09-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_church_calendar_public_hash_delete_churchevent"),
        ("finance", "0011_migrate_churchevent_to_calendarevent"),
    ]

    operations = [
        migrations.DeleteModel(name="ChurchEvent",),
    ]
