# Generated by Django 5.2.3 on 2026-09-09 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_delete_churchevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Características"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_items",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material/Equipamento",
                "verbose_name_plural": "Materiais/Equipamentos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "borrower_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Nome do tomador (quando não vinculado a um membro)",
                    ),
                ),
                ("borrowed_at", models.DateField(verbose_name="Data do empréstimo")),
                (
                    "expected_return",
                    models.DateField(verbose_name="Devolução prevista"),
                ),
                (
                    "returned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Devolvido em"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loans",
                        to="accounts.member",
                        verbose_name="Membro",
                    ),
                ),
                (
                    "returned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Baixa dada por",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="accounts.materialitem",
                        verbose_name="Material/Equipamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empréstimo de Material",
                "verbose_name_plural": "Empréstimos de Materiais",
                "ordering": ["-borrowed_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StorageLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nome do local"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_locations",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Local de Armazenamento",
                "verbose_name_plural": "Locais de Armazenamento",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="materialitem",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="accounts.storagelocation",
                verbose_name="Local de armazenamento",
            ),
        ),
        migrations.AddConstraint(
            model_name="storagelocation",
            constraint=models.UniqueConstraint(
                fields=("church", "name"), name="unique_church_storage_location"
            ),
        ),
    ]
