# Generated by Django 5.2.3 on 2026-09-09 23:50

import accounts.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_materialitem_loan_storagelocation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChurchMinutes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Título da ata"),
                ),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[
                            ("ASSEMBLEIA_GERAL", "Assembleia Geral"),
                            ("ASSEMBLEIA_EXTRAORDINARIA", "Assembleia Extraordinária"),
                            ("DIRETORIA", "Reunião da Diretoria"),
                            ("CONSELHO", "Reunião do Conselho"),
                            ("OUTRO", "Outro"),
                        ],
                        default="ASSEMBLEIA_GERAL",
                        max_length=30,
                        verbose_name="Tipo de reunião",
                    ),
                ),
                ("meeting_date", models.DateField(verbose_name="Data da reunião")),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="Local"),
                ),
                (
                    "recorder",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Redator (quem lavrou)"
                    ),
                ),
                (
                    "participants",
                    models.TextField(
                        blank=True, verbose_name="Participantes / presentes"
                    ),
                ),
                ("content", models.TextField(verbose_name="Texto da ata")),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=accounts.models.MinutesStorage(),
                        upload_to="minutes/",
                        verbose_name="PDF da ata",
                    ),
                ),
                (
                    "public_hash",
                    models.CharField(
                        default=None,
                        editable=False,
                        max_length=44,
                        null=True,
                        unique=True,
                        verbose_name="Hash público",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="minutes",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Redigida por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ata",
                "verbose_name_plural": "Atas",
                "ordering": ["-meeting_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="WorshipService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Data do culto")),
                (
                    "time",
                    models.TimeField(blank=True, null=True, verbose_name="Horário"),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("CELEBRACAO", "Culto de Celebração"),
                            ("DOUTRINA", "Culto de Doutrina"),
                            ("ORACAO", "Culto de Oração"),
                            ("VIGILIA", "Vigília"),
                            ("CEIA", "Ceia do Senhor"),
                            ("ESCOLA_BIBLICA", "Escola Bíblica"),
                            ("JOVENS", "Culto de Jovens"),
                            ("OUTRO", "Outro"),
                        ],
                        default="CELEBRACAO",
                        max_length=20,
                        verbose_name="Tipo de culto",
                    ),
                ),
                (
                    "presider",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Dirigente"
                    ),
                ),
                (
                    "preacher",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Pregador/ministrante"
                    ),
                ),
                (
                    "theme",
                    models.CharField(blank=True, max_length=200, verbose_name="Tema"),
                ),
                (
                    "scripture",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Texto bíblico"
                    ),
                ),
                (
                    "attendees",
                    models.PositiveIntegerField(default=0, verbose_name="Presentes"),
                ),
                (
                    "visitors",
                    models.PositiveIntegerField(default=0, verbose_name="Visitantes"),
                ),
                (
                    "conversions",
                    models.PositiveIntegerField(default=0, verbose_name="Conversões"),
                ),
                (
                    "offering",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Ofertas",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worship_services",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Culto",
                "verbose_name_plural": "Registros de Cultos",
                "ordering": ["-date", "-id"],
            },
        ),
    ]
