# Generated by Django 5.2.3 on 2026-09-10 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_churchminutes_worshipservice"),
    ]

    operations = [
        migrations.AddField(
            model_name="church",
            name="member_form_hash",
            field=models.CharField(
                blank=True,
                help_text="Hash usado no link genérico de cadastro de candidatos.",
                max_length=44,
                null=True,
                unique=True,
                verbose_name="Hash público do Formulário de Membros",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="public_hash",
            field=models.CharField(
                default=None,
                editable=False,
                help_text="Usado na URL pública do cartão de membro.",
                max_length=44,
                null=True,
                unique=True,
                verbose_name="Hash público do cartão",
            ),
        ),
        migrations.CreateModel(
            name="MemberSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_hash",
                    models.CharField(
                        help_text="Hash do cartão do membro ou do formulário genérico da igreja.",
                        max_length=44,
                        verbose_name="Hash do link de origem",
                    ),
                ),
                ("data", models.JSONField(verbose_name="Dados enviados")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente de revisão"),
                            ("APPROVED", "Aprovado"),
                            ("REJECTED", "Rejeitado"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Revisado em"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Enviado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_submissions",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="accounts.member",
                        verbose_name="Membro (se submissão vem do cartão)",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Revisado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submissão de membro",
                "verbose_name_plural": "Submissões de membros",
                "ordering": ["-created_at"],
            },
        ),
    ]
