# Generated by Django 5.2.3 on 2026-09-11 15:15

import cloudinary_storage.storage
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_church_member_form_hash_member_public_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="church",
            name="logo",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to=core.storage.church_logo_upload_to,
                verbose_name="Logo",
            ),
        ),
        migrations.AddField(
            model_name="materialitem",
            name="manual",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to=core.storage.church_upload_to("materials/manuals"),
                verbose_name="Manual / Documentação",
            ),
        ),
        migrations.AddField(
            model_name="materialitem",
            name="photo",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to=core.storage.church_upload_to("materials/photos"),
                verbose_name="Foto",
            ),
        ),
        migrations.AlterField(
            model_name="churchminutes",
            name="pdf",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to=core.storage.church_upload_to("minutes"),
                verbose_name="PDF da ata",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="photo",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to=core.storage.church_upload_to("members"),
                verbose_name="Foto",
            ),
        ),
        migrations.AlterField(
            model_name="memberdocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("RESIDENCE_PROOF", "Comprovante de Residência"),
                    ("OTHER", "Outro"),
                ],
                max_length=20,
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AlterField(
            model_name="memberdocument",
            name="file",
            field=models.FileField(
                max_length=255,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to=core.storage.church_upload_to("member_documents"),
                verbose_name="Arquivo",
            ),
        ),
    ]
