# Generated by Django 5.2.3 on 2026-09-11 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0020_church_logo_materialitem_manual_materialitem_photo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="church",
            name="default_pix_key",
            field=models.CharField(
                blank=True,
                help_text="Sugerida no cadastro de links do tipo PIX.",
                max_length=100,
                null=True,
                verbose_name="Chave PIX padrão",
            ),
        ),
        migrations.AddField(
            model_name="church",
            name="default_pix_type",
            field=models.CharField(
                blank=True,
                help_text="CNPJ, CPF, Telefone, E-mail ou Chave Aleatória.",
                max_length=20,
                null=True,
                verbose_name="Tipo da Chave PIX padrão",
            ),
        ),
        migrations.AddField(
            model_name="church",
            name="links_hash",
            field=models.CharField(
                blank=True,
                help_text="Hash alternativo para acessar a página pública (compartilhamento seguro).",
                max_length=64,
                null=True,
                verbose_name="Hash público dos Links",
            ),
        ),
        migrations.AddField(
            model_name="church",
            name="public_links_enabled",
            field=models.BooleanField(
                default=True, verbose_name="Página pública de links habilitada"
            ),
        ),
        migrations.AddField(
            model_name="church",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Identificador amigável da página pública de links (/p/{slug}).",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Slug público",
            ),
        ),
        migrations.AddField(
            model_name="church",
            name="theme_color",
            field=models.CharField(
                default="#1c7ed6",
                help_text="Cor primária usada na página pública de links.",
                max_length=20,
                verbose_name="Cor do Tema (página pública)",
            ),
        ),
        migrations.CreateModel(
            name="ChurchPublicLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Título")),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="URL externa (tipos CUSTOM/WHATSAPP/YOUTUBE/MAPS/INSTAGRAM).",
                        max_length=500,
                        verbose_name="URL",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("CUSTOM", "Personalizado"),
                            ("PIX", "Chave PIX"),
                            ("WHATSAPP", "WhatsApp"),
                            ("YOUTUBE", "YouTube"),
                            ("MAPS", "Localização / Mapa"),
                            ("INSTAGRAM", "Instagram"),
                            ("CALENDAR", "Agenda de Cultos"),
                            ("MEMBERSHIP", "Ficha de Membro / Cadastro"),
                        ],
                        default="CUSTOM",
                        max_length=20,
                        verbose_name="Tipo do link",
                    ),
                ),
                (
                    "pix_key",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Chave PIX"
                    ),
                ),
                (
                    "pix_type",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Tipo da chave PIX",
                    ),
                ),
                (
                    "icon_key",
                    models.CharField(
                        blank=True,
                        help_text="Chave do ícone (tabler): brand-whatsapp, brand-youtube, ...",
                        max_length=50,
                        null=True,
                        verbose_name="Ícone",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "highlight",
                    models.BooleanField(
                        default=False,
                        help_text="Exibe o link com borda destacada/pulsante na página pública.",
                        verbose_name="Destaque visual",
                    ),
                ),
                (
                    "click_count",
                    models.PositiveIntegerField(default=0, verbose_name="Cliques"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_links",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Link público",
                "verbose_name_plural": "Links públicos",
                "ordering": ["order", "id"],
            },
        ),
    ]
