# Generated by Django 5.2.3 on 2026-09-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_backfill_church_slug_links_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="churchpubliclink",
            name="address_cep",
            field=models.CharField(
                blank=True, default="", max_length=9, verbose_name="CEP"
            ),
        ),
        migrations.AddField(
            model_name="churchpubliclink",
            name="address_city",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Cidade"
            ),
        ),
        migrations.AddField(
            model_name="churchpubliclink",
            name="address_neighborhood",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Bairro"
            ),
        ),
        migrations.AddField(
            model_name="churchpubliclink",
            name="address_number",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Número"
            ),
        ),
        migrations.AddField(
            model_name="churchpubliclink",
            name="address_state",
            field=models.CharField(
                blank=True, default="", max_length=2, verbose_name="UF"
            ),
        ),
        migrations.AddField(
            model_name="churchpubliclink",
            name="address_street",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Logradouro"
            ),
        ),
        migrations.AddField(
            model_name="churchpubliclink",
            name="pix_amount_mode",
            field=models.CharField(
                choices=[
                    ("OPEN", "Valor livre"),
                    ("FIXED", "Valor fixo"),
                    ("GRID", "Grade de valores"),
                ],
                default="OPEN",
                help_text="OPEN = usuário digita o valor; FIXED = valor único; GRID = botões com valores pré-definidos.",
                max_length=10,
                verbose_name="Modo de valor PIX",
            ),
        ),
        migrations.AddField(
            model_name="churchpubliclink",
            name="pix_fixed_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="Usado quando pix_amount_mode = FIXED.",
                max_digits=8,
                null=True,
                verbose_name="Valor fixo PIX",
            ),
        ),
        migrations.AddField(
            model_name="churchpubliclink",
            name="pix_grid_amounts",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Botões de valor exibidos quando pix_amount_mode = GRID (padrão: 30, 50, 100, 200).",
                null=True,
                verbose_name="Valores PIX pré-definidos",
            ),
        ),
        migrations.AddField(
            model_name="churchpubliclink",
            name="pix_open_amount",
            field=models.BooleanField(
                default=True,
                help_text='Exibe a opção "Outro valor" além dos presets quando pix_amount_mode = GRID.',
                verbose_name="Permitir valor livre no grid",
            ),
        ),
        migrations.AddField(
            model_name="churchpubliclink",
            name="whatsapp_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Só dígitos (com DDI). O link wa.me é montado automaticamente.",
                max_length=20,
                verbose_name="Número do WhatsApp",
            ),
        ),
    ]
