# Generated by Django 5.2.3 on 2026-09-11 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_churchpubliclink_address_cep_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrowthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nome do GC")),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Segunda-feira"),
                            (1, "Terça-feira"),
                            (2, "Quarta-feira"),
                            (4, "Sexta-feira"),
                        ],
                        default=1,
                        verbose_name="Dia de encontro",
                    ),
                ),
                ("time", models.TimeField(verbose_name="Horário")),
                ("address", models.CharField(max_length=250, verbose_name="Endereço")),
                (
                    "radius_meters",
                    models.PositiveIntegerField(
                        default=1000, verbose_name="Raio de cobertura (m)"
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="Latitude"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Longitude"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="growth_groups",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hosted_growth_groups",
                        to="accounts.member",
                        verbose_name="Anfitrião",
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="linked_growth_groups",
                        to="accounts.member",
                        verbose_name="Líder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo de Crescimento",
                "verbose_name_plural": "Grupos de Crescimento",
                "ordering": ["weekday", "name"],
            },
        ),
    ]
