# Generated by Django 5.2.3 on 2026-09-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_growthgroup"),
    ]

    operations = [
        migrations.RemoveField(model_name="growthgroup", name="address",),
        migrations.AddField(
            model_name="growthgroup",
            name="cep",
            field=models.CharField(
                blank=True, default="", max_length=9, verbose_name="CEP"
            ),
        ),
        migrations.AddField(
            model_name="growthgroup",
            name="city",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Cidade"
            ),
        ),
        migrations.AddField(
            model_name="growthgroup",
            name="complement",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Complemento"
            ),
        ),
        migrations.AddField(
            model_name="growthgroup",
            name="neighborhood",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Bairro"
            ),
        ),
        migrations.AddField(
            model_name="growthgroup",
            name="number",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Número"
            ),
        ),
        migrations.AddField(
            model_name="growthgroup",
            name="state",
            field=models.CharField(
                blank=True, default="", max_length=2, verbose_name="UF"
            ),
        ),
        migrations.AddField(
            model_name="growthgroup",
            name="street",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="Rua / Avenida"
            ),
        ),
    ]
