# Generated by Django 5.2.3 on 2026-09-12 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_remove_growthgroup_address_growthgroup_cep_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="last_contact_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Último contato (WhatsApp)"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="lifecycle_stage",
            field=models.CharField(
                choices=[
                    ("VISITOR", "Visitante / Novo"),
                    ("INTEGRATION", "Em Integração"),
                    ("ACTIVE", "Membro Ativo"),
                    ("ABSENT_CARE", "Ausência / Cuidado Pastoral"),
                    ("TRANSITION", "Em Transição / Afastado"),
                ],
                default="ACTIVE",
                max_length=20,
                verbose_name="Estágio do Membro",
            ),
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Título")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BIRTHDAY", "Aniversário"),
                            ("WELCOME", "Boas-Vindas"),
                            ("CARE", "Cuidado / Ausência"),
                            ("VERSE", "Versículo"),
                            ("CARD_EXPIRING", "Carteirinha a Vencer"),
                            ("CUSTOM", "Personalizado"),
                        ],
                        default="CUSTOM",
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Tokens disponíveis: {{NOME}}, {{PRIMEIRO_NOME}}, {{IGREJA}}, {{CIDADE}}.",
                        verbose_name="Conteúdo da mensagem",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_templates",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de Mensagem",
                "verbose_name_plural": "Modelos de Mensagem",
                "ordering": ["category", "title"],
            },
        ),
        migrations.CreateModel(
            name="MemberContactLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BIRTHDAY", "Aniversário"),
                            ("WELCOME", "Boas-Vindas"),
                            ("CARE", "Cuidado / Ausência"),
                            ("VERSE", "Versículo"),
                            ("CARD_EXPIRING", "Carteirinha a Vencer"),
                            ("CUSTOM", "Personalizado"),
                        ],
                        default="CUSTOM",
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "message_content",
                    models.TextField(
                        blank=True, default="", verbose_name="Conteúdo enviado"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_contact_log",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
                (
                    "contacted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Contatado por",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_log",
                        to="accounts.member",
                        verbose_name="Membro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contato via WhatsApp",
                "verbose_name_plural": "Contatos via WhatsApp",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["church", "created_at"],
                        name="accounts_me_church__b06720_idx",
                    )
                ],
            },
        ),
    ]
