# Generated by Django 5.2.3 on 2026-09-12 19:14

import cloudinary_storage.storage
import core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_default_message_templates"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="Nome do modelo"),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("BAPTISM", "Batismo nas Águas"),
                            ("CHILD_PRESENTATION", "Apresentação de Crianças"),
                            ("MEMBERSHIP_COURSE", "Curso de Membresia"),
                            ("CUSTOM", "Personalizado"),
                        ],
                        default="CUSTOM",
                        max_length=30,
                        verbose_name="Tipo de certificado",
                    ),
                ),
                (
                    "layout_mode",
                    models.CharField(
                        choices=[
                            ("SYSTEM_DEFAULT", "Padrão do Sistema (Layout Clássico)"),
                            ("CUSTOM_IMAGE", "Imagem de Fundo / Moldura (PNG/JPG)"),
                            ("BASE_PDF", "Documento Base em PDF"),
                        ],
                        default="SYSTEM_DEFAULT",
                        max_length=20,
                        verbose_name="Modo de layout",
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                        upload_to=core.storage.church_upload_to(
                            "certificate_templates"
                        ),
                        verbose_name="Imagem de fundo / moldura",
                    ),
                ),
                (
                    "base_pdf",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                        upload_to=core.storage.church_upload_to(
                            "certificate_templates"
                        ),
                        verbose_name="Documento base em PDF",
                    ),
                ),
                (
                    "default_verse",
                    models.TextField(
                        blank=True, default="", verbose_name="Versículo padrão"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_templates",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de Certificado",
                "verbose_name_plural": "Modelos de Certificados",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EcclesiasticalCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("BAPTISM", "Batismo nas Águas"),
                            ("CHILD_PRESENTATION", "Apresentação de Crianças"),
                            ("MEMBERSHIP_COURSE", "Curso de Membresia"),
                            ("CUSTOM", "Personalizado"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de certificado",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(max_length=200, verbose_name="Destinatário"),
                ),
                ("event_date", models.DateField(verbose_name="Data do evento")),
                (
                    "officiant_name",
                    models.CharField(
                        max_length=150, verbose_name="Ministro celebrante"
                    ),
                ),
                (
                    "father_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Nome do Pai",
                    ),
                ),
                (
                    "mother_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Nome da Mãe",
                    ),
                ),
                (
                    "scripture_verse",
                    models.TextField(
                        blank=True, default="", verbose_name="Versículo bíblico"
                    ),
                ),
                (
                    "registry_book",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Livro de Registro",
                    ),
                ),
                (
                    "registry_page",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Folha / Página",
                    ),
                ),
                (
                    "registry_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Número do Termo",
                    ),
                ),
                (
                    "generated_pdf",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                        upload_to=core.storage.church_upload_to("certificates"),
                        verbose_name="PDF emitido",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Emitido em"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Emitido por",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates",
                        to="accounts.member",
                        verbose_name="Membro (opcional)",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_certificates",
                        to="accounts.certificatetemplate",
                        verbose_name="Modelo utilizado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado Eclesiástico",
                "verbose_name_plural": "Certificados Eclesiásticos",
                "ordering": ["-created_at"],
            },
        ),
    ]
