# Generated by Django 5.2.3 on 2026-09-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0028_certificatetemplate_ecclesiasticalcertificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="growthgroup",
            name="category",
            field=models.CharField(
                choices=[
                    ("ADULTS", "Adultos / Famílias"),
                    ("YOUTH", "Jovens"),
                    ("TEENS", "Adolescentes"),
                    ("WOMEN", "Mulheres"),
                    ("MEN", "Homens"),
                    ("MIXED", "Misto / Geral"),
                ],
                default="MIXED",
                max_length=20,
                verbose_name="Categoria",
            ),
        ),
        migrations.AddField(
            model_name="growthgroup",
            name="is_full",
            field=models.BooleanField(
                default=False,
                help_text='Quando ligado, o card público mostra "Grupo cheio" e o botão WhatsApp vira "Falar com o Líder" (não "Quero Participar").',
                verbose_name="Está cheio (sem vagas)",
            ),
        ),
    ]
