# Generated by Django 5.2.3 on 2026-09-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0029_growthgroup_category_growthgroup_is_full"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificatetemplate",
            name="fields_layout",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
