# Generated by Django 5.2.3 on 2026-09-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0030_certificatetemplate_fields_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="church",
            name="card_theme",
            field=models.CharField(
                choices=[("CLASSIC", "Clássico"), ("BLACK_PREMIUM", "Black Premium")],
                default="CLASSIC",
                max_length=20,
                verbose_name="Tema da Carteirinha",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="whatsapp_public",
            field=models.BooleanField(
                default=False, verbose_name="Exibir WhatsApp no perfil público"
            ),
        ),
    ]
