# Generated by Django 5.2.3 on 2026-09-14 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0031_church_card_theme_member_whatsapp_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="churchmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("PASTOR", "Pastor(a)"),
                    ("SECRETARIA", "Secretário(a)"),
                    ("TESOUREIRO", "Tesoureiro(a)"),
                    ("INTERCESSAO", "Intercessor(a)"),
                ],
                max_length=20,
                verbose_name="Papel",
            ),
        ),
        migrations.CreateModel(
            name="PastoralVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_name",
                    models.CharField(
                        blank=True,
                        help_text="Usado quando a visita é a um ponto avulso (sem membro cadastrado).",
                        max_length=150,
                        verbose_name="Nome do visitado",
                    ),
                ),
                (
                    "target_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone do visitado"
                    ),
                ),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Rota / Rotina"),
                            ("ILLNESS", "Doença"),
                            ("BEREAVEMENT", "Luto"),
                            ("NEW_CONVERT", "Novo Convertido"),
                            ("SOCIAL_AID", "Ação Social"),
                            ("SPECIAL", "Especial"),
                        ],
                        default="ROUTINE",
                        max_length=20,
                        verbose_name="Tipo de visita",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planejada"),
                            ("COMPLETED", "Realizada"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        default="PLANNED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "competence_year",
                    models.PositiveSmallIntegerField(verbose_name="Ano da competência"),
                ),
                (
                    "competence_month",
                    models.PositiveSmallIntegerField(verbose_name="Mês da competência"),
                ),
                ("scheduled_date", models.DateField(verbose_name="Data agendada")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Realizada em"
                    ),
                ),
                (
                    "visited_by",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Visitadores"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Relatório da visita"),
                ),
                (
                    "needs_followup",
                    models.BooleanField(
                        default=False, verbose_name="Requer acompanhamento"
                    ),
                ),
                ("cep", models.CharField(blank=True, max_length=9, verbose_name="CEP")),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Logradouro"
                    ),
                ),
                (
                    "number",
                    models.CharField(blank=True, max_length=20, verbose_name="Número"),
                ),
                (
                    "neighborhood",
                    models.CharField(blank=True, max_length=100, verbose_name="Bairro"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
                ),
                (
                    "state",
                    models.CharField(blank=True, max_length=2, verbose_name="UF"),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="Latitude"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Longitude"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pastoral_visits",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pastoral_visits_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pastoral_visits",
                        to="accounts.member",
                        verbose_name="Membro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visita Pastoral",
                "verbose_name_plural": "Visitas Pastorais",
                "ordering": ["-scheduled_date", "-created_at"],
            },
        ),
    ]
