# Generated by Django 5.2.3 on 2026-09-14 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0032_alter_churchmembership_role_pastoralvisit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="churchmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("PASTOR", "Pastor(a)"),
                    ("SECRETARIA", "Secretário(a)"),
                    ("TESOUREIRO", "Tesoureiro(a)"),
                    ("INTERCESSAO", "Intercessão & Visitação"),
                ],
                max_length=20,
                verbose_name="Papel",
            ),
        ),
        migrations.CreateModel(
            name="PrayerRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requester_name",
                    models.CharField(
                        max_length=150, verbose_name="Nome do solicitante"
                    ),
                ),
                (
                    "requester_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=25,
                        verbose_name="Telefone do solicitante",
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=False, verbose_name="Solicita anonimato"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HEALTH", "Saúde / Enfermidade"),
                            ("FAMILY", "Família & Lar"),
                            ("SPIRITUAL", "Vida Espiritual"),
                            ("FINANCIAL", "Emprego & Provisão"),
                            ("GRIEF", "Luto & Consolo"),
                            ("THANKSGIVING", "Ações de Graças"),
                            ("OTHER", "Outro Motivo"),
                        ],
                        default="SPIRITUAL",
                        max_length=30,
                        verbose_name="Categoria do pedido",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Descrição / Motivo da oração"),
                ),
                (
                    "wants_visit",
                    models.BooleanField(
                        default=False, verbose_name="Deseja visita pastoral"
                    ),
                ),
                (
                    "neighborhood",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Bairro"
                    ),
                ),
                (
                    "preferred_period",
                    models.CharField(
                        choices=[
                            ("ANY", "Qualquer Horário"),
                            ("MORNING", "Manhã"),
                            ("AFTERNOON", "Tarde"),
                            ("NIGHT", "Noite"),
                        ],
                        default="ANY",
                        max_length=20,
                        verbose_name="Período preferido",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Novo / Aguardando"),
                            ("PRAYING", "Em Oração"),
                            ("VISIT_SCHEDULED", "Visita Agendada"),
                            ("ANSWERED", "Respondido / Testemunho"),
                            ("ARCHIVED", "Arquivado"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "pastoral_notes",
                    models.TextField(
                        blank=True, default="", verbose_name="Anotações pastorais"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_prayer_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável",
                    ),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prayer_requests",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido de Oração",
                "verbose_name_plural": "Pedidos de Oração",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="pastoralvisit",
            name="prayer_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visits",
                to="accounts.prayerrequest",
                verbose_name="Pedido de Oração Vinculado",
            ),
        ),
    ]
