# Generated by Django 5.2.3 on 2026-09-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0033_alter_churchmembership_role_prayerrequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prayerrequest",
            name="cep",
            field=models.CharField(
                blank=True, default="", max_length=9, verbose_name="CEP"
            ),
        ),
        migrations.AddField(
            model_name="prayerrequest",
            name="city",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Cidade"
            ),
        ),
        migrations.AddField(
            model_name="prayerrequest",
            name="number",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Número"
            ),
        ),
        migrations.AddField(
            model_name="prayerrequest",
            name="state",
            field=models.CharField(
                blank=True, default="", max_length=2, verbose_name="Estado (UF)"
            ),
        ),
        migrations.AddField(
            model_name="prayerrequest",
            name="street",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Logradouro"
            ),
        ),
        migrations.AlterField(
            model_name="churchpubliclink",
            name="link_type",
            field=models.CharField(
                choices=[
                    ("CUSTOM", "Personalizado"),
                    ("PIX", "Chave PIX"),
                    ("WHATSAPP", "WhatsApp"),
                    ("YOUTUBE", "YouTube"),
                    ("MAPS", "Localização / Mapa"),
                    ("INSTAGRAM", "Instagram"),
                    ("CALENDAR", "Agenda de Cultos"),
                    ("MEMBERSHIP", "Ficha de Membro / Cadastro"),
                    ("PRAYER", "Pedido de Oração"),
                ],
                default="CUSTOM",
                max_length=20,
                verbose_name="Tipo do link",
            ),
        ),
    ]
