# Generated by Django 5.2.3 on 2026-09-14 21:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

EBD_TEMPLATES = [
    {
        'title': 'Aviso de Aula (EBD)',
        'category': 'EBD_CLASS_ANNOUNCEMENT',
        'content': (
            '🙏 {{PRIMEIRO_NOME}}, amanhã temos Escola Bíblica Dominical! '
            'Esperamos você na classe {{CLASSE}}.\n\n'
            'Tema da próxima aula: {{TEMA}}\nUm abraço de toda a turma 💙'
        ),
    },
    {
        'title': 'Resgate de Ausência (EBD)',
        'category': 'EBD_ABSENCE_RESCUE',
        'content': (
            '💙 Oi, {{PRIMEIRO_NOME}}! Sentimos a sua falta na EBD, na classe '
            '{{CLASSE}}. Queremos saber como você está. Se precisar conversar, '
            'orar ou de qualquer ajuda, estamos bem pertinho. Um abraço da {{IGREJA}}.'
        ),
    },
    {
        'title': 'Aniversariante da Semana (EBD)',
        'category': 'EBD_BIRTHDAY',
        'content': (
            '🎉 Feliz aniversário, {{PRIMEIRO_NOME}}! Que Deus abençoe o seu novo '
            'ano de vida com muita paz e alegria.\n\nÉ um presente ter você na '
            'classe {{CLASSE}}. Com carinho, {{PROFESSOR}} 🎂'
        ),
    },
]


def seed_ebd_templates(apps, schema_editor):
    Church = apps.get_model('accounts', 'Church')
    MessageTemplate = apps.get_model('accounts', 'MessageTemplate')
    for church in Church.objects.iterator():
        for data in EBD_TEMPLATES:
            defaults = {k: v for k, v in data.items() if k != 'category'}
            MessageTemplate.objects.get_or_create(
                church=church,
                category=data['category'],
                defaults=defaults,
            )


def remove_ebd_templates(apps, schema_editor):
    MessageTemplate = apps.get_model('accounts', 'MessageTemplate')
    MessageTemplate.objects.filter(
        created_by__isnull=True,
        category__in=[t['category'] for t in EBD_TEMPLATES],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0034_prayerrequest_cep_prayerrequest_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membercontactlog",
            name="category",
            field=models.CharField(
                choices=[
                    ("BIRTHDAY", "Aniversário"),
                    ("WELCOME", "Boas-Vindas"),
                    ("CARE", "Cuidado / Ausência"),
                    ("VERSE", "Versículo"),
                    ("CARD_EXPIRING", "Carteirinha a Vencer"),
                    ("EBD_CLASS_ANNOUNCEMENT", "Aviso de Aula (EBD)"),
                    ("EBD_ABSENCE_RESCUE", "Resgate de Ausência (EBD)"),
                    ("EBD_BIRTHDAY", "Aniversariante da Semana (EBD)"),
                    ("CUSTOM", "Personalizado"),
                ],
                default="CUSTOM",
                max_length=30,
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="messagetemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("BIRTHDAY", "Aniversário"),
                    ("WELCOME", "Boas-Vindas"),
                    ("CARE", "Cuidado / Ausência"),
                    ("VERSE", "Versículo"),
                    ("CARD_EXPIRING", "Carteirinha a Vencer"),
                    ("EBD_CLASS_ANNOUNCEMENT", "Aviso de Aula (EBD)"),
                    ("EBD_ABSENCE_RESCUE", "Resgate de Ausência (EBD)"),
                    ("EBD_BIRTHDAY", "Aniversariante da Semana (EBD)"),
                    ("CUSTOM", "Personalizado"),
                ],
                default="CUSTOM",
                max_length=30,
                verbose_name="Categoria",
            ),
        ),
        migrations.CreateModel(
            name="SundaySchoolClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="Nome da classe"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CHILDREN", "Infantil"),
                            ("TEENS", "Adolescentes"),
                            ("YOUTH", "Jovens"),
                            ("ADULTS", "Adultos"),
                            ("COUPLES", "Casais"),
                            ("DISCIPLESHIP", "Discipulado"),
                        ],
                        default="ADULTS",
                        max_length=20,
                        verbose_name="Categoria / Faixa",
                    ),
                ),
                (
                    "teacher_name",
                    models.CharField(max_length=150, verbose_name="Professor(a)"),
                ),
                (
                    "co_teacher_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Professor(a) auxiliar",
                    ),
                ),
                (
                    "room_location",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Sala / Local",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criada em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizada em"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sunday_school_classes",
                        to="accounts.church",
                        verbose_name="Igreja",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criada por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classe de EBD",
                "verbose_name_plural": "Classes de EBD",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SundaySchoolEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_name",
                    models.CharField(max_length=150, verbose_name="Nome do aluno"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=25,
                        verbose_name="Telefone / WhatsApp",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "joined_at",
                    models.DateField(auto_now_add=True, verbose_name="Matriculado em"),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ebd_enrollments",
                        to="accounts.member",
                        verbose_name="Membro vinculado",
                    ),
                ),
                (
                    "sunday_school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="accounts.sundayschoolclass",
                        verbose_name="Classe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matrícula de EBD",
                "verbose_name_plural": "Matrículas de EBD",
                "ordering": ["student_name"],
            },
        ),
        migrations.CreateModel(
            name="SundaySchoolSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Data da aula")),
                (
                    "topic",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Tema da aula",
                    ),
                ),
                (
                    "bibles_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Bíblias presentes"
                    ),
                ),
                (
                    "magazines_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Revistas trazidas"
                    ),
                ),
                (
                    "visitors_count",
                    models.PositiveIntegerField(default=0, verbose_name="Visitantes"),
                ),
                (
                    "offering_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Oferta",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", verbose_name="Observações"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criada em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizada em"),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrada por",
                    ),
                ),
                (
                    "sunday_school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="accounts.sundayschoolclass",
                        verbose_name="Classe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aula de EBD",
                "verbose_name_plural": "Aulas de EBD",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SundaySchoolAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_present",
                    models.BooleanField(default=False, verbose_name="Presente"),
                ),
                (
                    "brought_bible",
                    models.BooleanField(default=False, verbose_name="Trouxe Bíblia"),
                ),
                (
                    "brought_magazine",
                    models.BooleanField(default=False, verbose_name="Trouxe Revista"),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="accounts.sundayschoolenrollment",
                        verbose_name="Matrícula",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="accounts.sundayschoolsession",
                        verbose_name="Aula",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presença de EBD",
                "verbose_name_plural": "Presenças de EBD",
                "ordering": ["enrollment__student_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="sundayschoolsession",
            constraint=models.UniqueConstraint(
                fields=("sunday_school_class", "date"),
                name="unique_session_per_class_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="sundayschoolattendance",
            constraint=models.UniqueConstraint(
                fields=("session", "enrollment"),
                name="unique_attendance_per_session_enrollment",
            ),
        ),
        migrations.RunPython(seed_ebd_templates, remove_ebd_templates),
    ]
