# Generated by Django 5.2.3 on 2026-09-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0035_alter_membercontactlog_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="churchmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("PASTOR", "Pastor(a)"),
                    ("SECRETARIA", "Secretário(a)"),
                    ("TESOUREIRO", "Tesoureiro(a)"),
                    ("INTERCESSAO", "Intercessão & Visitação"),
                    ("LOUVOR", "Líder de Louvor & Música"),
                    ("MUSICO", "Músico / Voluntário"),
                ],
                max_length=20,
                verbose_name="Papel",
            ),
        ),
    ]
