# Generated by Django 5.2.3 on 2026-09-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0036_alter_churchmembership_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="churchpubliclink",
            name="link_type",
            field=models.CharField(
                choices=[
                    ("CUSTOM", "Personalizado"),
                    ("PIX", "Chave PIX"),
                    ("WHATSAPP", "WhatsApp"),
                    ("YOUTUBE", "YouTube"),
                    ("MAPS", "Localização / Mapa"),
                    ("INSTAGRAM", "Instagram"),
                    ("CALENDAR", "Agenda de Cultos"),
                    ("MEMBERSHIP", "Ficha de Membro / Cadastro"),
                    ("PRAYER", "Pedido de Oração"),
                    ("GROWTH_GROUPS", "Grupos de Crescimento"),
                ],
                default="CUSTOM",
                max_length=20,
                verbose_name="Tipo do link",
            ),
        ),
    ]
