# Generated by Django 5.2.3 on 2026-09-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0037_alter_churchpubliclink_link_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="borrower_phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=25,
                verbose_name="Telefone do tomador (quando não vinculado a um membro)",
            ),
        ),
        migrations.AlterField(
            model_name="churchmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("PASTOR", "Pastor(a)"),
                    ("SECRETARIA", "Secretário(a)"),
                    ("TESOUREIRO", "Tesoureiro(a)"),
                    ("INTERCESSAO", "Intercessão & Visitação"),
                    ("LOUVOR", "Líder de Louvor & Música"),
                    ("MUSICO", "Músico / Voluntário"),
                    ("PROFESSOR_EBD", "Professor(a) de EBD"),
                ],
                max_length=20,
                verbose_name="Papel",
            ),
        ),
    ]
