# Generated by Django 5.2.3 on 2026-09-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0038_loan_borrower_phone_alter_churchmembership_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="prayerrequest",
            name="complement",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Complemento"
            ),
        ),
    ]
