# Generated by Django 5.2.3 on 2026-09-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0039_prayerrequest_complement"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="growthgroup",
            index=models.Index(
                fields=["church", "weekday"], name="acct_growth_church_weekday_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["church", "status"], name="acct_member_church_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["church", "created_at"], name="acct_member_church_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pastoralvisit",
            index=models.Index(
                fields=["church", "competence_year", "competence_month"],
                name="acct_visit_church_comp_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pastoralvisit",
            index=models.Index(
                fields=["church", "status", "scheduled_date"],
                name="acct_visit_church_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prayerrequest",
            index=models.Index(
                fields=["church", "status", "created_at"],
                name="acct_prayer_church_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="worshipservice",
            index=models.Index(
                fields=["church", "date"], name="acct_worship_church_date_idx"
            ),
        ),
    ]
