"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from datetime import timedelta
from decouple import config, Csv

import logging

import cloudinary
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega o .env (raiz do backend) para os.environ. Necessário pois a
# configuração de e-mail (SMTP), DATABASE_URL etc. são lidos de os.environ.
from dotenv import load_dotenv  # noqa: E402
load_dotenv(BASE_DIR / '.env')

# Durante a suíte de testes (manage.py test) as mídias vão para o filesystem
# local (core/storage.py) — mantém os testes herméticos, sem rede/Cloudinary.
if 'test' in sys.argv:
    os.environ.setdefault('USE_LOCAL_MEDIA_STORAGE', '1')

SECRET_KEY = config('SECRET_KEY', default='django-insecure-dev-key')
DEBUG = config('DEBUG', default=True, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())
# No Heroku (DYNO presente) o domínio "<app>.herokuapp.com" é sempre válido.
if os.environ.get('DYNO'):
    ALLOWED_HOSTS.append(f"{os.environ.get('HEROKU_APP_NAME') or 'app'}.herokuapp.com")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",


    # Terceiros
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'cloudinary_storage',

    # Apps locais
    'accounts',
    'finance',
    'music',
]

# Modelo de Usuário Customizado (essencial definir ANTES do primeiro migrate)
AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Usa DATABASE_URL quando definido (produção/Docker com Postgres).
# Sem a variável, mantém SQLite local para desenvolvimento rápido.
DATABASES = {
    "default": dj_database_url.config(
        default="sqlite:///" + str(BASE_DIR / "db.sqlite3"),
        conn_max_age=600,
        ssl_require=False,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True


# Arquivos Estáticos e Mídia
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS — aceita FRONTEND_URL (legado) ou uma lista CSV via CORS_ALLOWED_ORIGINS.
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default=config('FRONTEND_URL', default='http://localhost:3000'),
    cast=Csv(),
)
CORS_ALLOW_CREDENTIALS = True

# Segurança de produção (Heroku/container): termina HTTPS no proxy e liga cookies seguros.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# DRF & JWT
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),   # Sessão de 7 dias
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_AUTHENTICATION_RULE': (
        'accounts.authentication.custom_user_authentication_rule'
    ),
}



EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
# Para Gmail SMTP o "from" precisa ser a própria conta autenticada
# (EMAIL_HOST_USER). Só usamos um from genérico se houver um explícito.
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@idb.org.br'
)

FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000')

PDF_ENGINE = os.getenv('PDF_ENGINE', 'xhtml2pdf')

# Cloudinary (armazenamento de mídia) — credenciais SEMPRE vêm do ambiente.
# Nada de credenciais hardcoded: em produção (DEBUG=False) a ausência das
# variáveis encerra o boot com erro explícito.
_cloud_name = os.environ.get('CLOUDINARY_CLOUD_NAME', '')
_cloud_api_key = os.environ.get('CLOUDINARY_API_KEY', '')
_cloud_api_secret = os.environ.get('CLOUDINARY_API_SECRET', '')

if not DEBUG and not all((_cloud_name, _cloud_api_key, _cloud_api_secret)):
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        'Cloudinary não configurado. Defina CLOUDINARY_CLOUD_NAME, '
        'CLOUDINARY_API_KEY e CLOUDINARY_API_SECRET no .env.'
    )

cloudinary.config(
    cloud_name=_cloud_name,
    api_key=_cloud_api_key,
    api_secret=_cloud_api_secret,
)

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': _cloud_name,
    'API_KEY': _cloud_api_key,
    'API_SECRET': _cloud_api_secret,
    'SECURE': True,
}


DOCKER_RUN = config('DOCKER_RUN', default=os.getenv('DOCKER_RUN', 'False'), cast=bool)